### ISSUE TITLE
Large integers are parsed incorrectly 

### ISSUE THREAD

**Issue by Kreastr** [Penlect/line-protocol-parser#1]
Some of large integer numbers that belong to valid subset for InfluxDb get parsed into negative values signifying integer overflow in conversion.

I.e. the following line

mem_load,host=hp active=5661716480i,available=11036143616i,buffers=1356238848i,cached=5868056576i,free=3734855680i,inactive=5180370944i,percent=30.0,shared=190390272i,slab=833347584i,total=15758827520i,used=4799676416i 1579879396287309824

Gets converted into this dictionary

{'measurement': 'mem_load', 'tags': {'host': 'hp'}, 'fields': {'used': 504709120, 'total': -1421041664, 'slab': 833347584, 'shared': 190390272, 'percent': 30.0, 'inactive': 885403648, 'free': -560111616, 'cached': 1573089280, 'buffers': 1356238848, 'available': -1848758272, 'active': 1366749184}, 'time': 1579879396287309824}

Fields total, free and available are incorrectly parsed.

**Comment by Penlect** [comment]
Thank you for the bug report! I located and removed the implicit conversion. I've added a test case for this and uploaded a new release (1.0.1) to PyPI. I'm surprised I missed to test this before.
