### ISSUE TITLE
Timestamp should be optional

### ISSUE THREAD

**Issue by BenMatase** [Penlect/line-protocol-parser#4]
I'm seeing this behavior:
```
>>> parse_line('measurement field=1i')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_line_protocol_parser.LineFormatError: Failed to parse value of field.
>>> parse_line('measurement field=1i 1')
{'measurement': 'measurement', 'tags': {}, 'fields': {'field': 1}, 'time': 1}
```
The [line protocol docs](https://v2.docs.influxdata.com/v2.0/reference/syntax/line-protocol/#timestamp) says that timestamp is optional. 

Also the error message is misleading because it makes you think something is wrong with a field, but I guess that point is moot if the timestamp is made optional.

**Comment by Penlect** [comment]
@chinese-soup Your pull request is included in release 1.1.0. New wheels have been uploaded to PyPI.
