### ISSUE TITLE
Uinteger format not supported in the parser

### ISSUE THREAD

**Issue by DIZI-BAREILLE** [Penlect/line-protocol-parser#8]
**Description**
Hello, I tried to parse a Uinteger value, but it seems it's not possible. 

**Steps to reproduce**
Here are the steps to reproduce the error: 
1. Parse a message with a Uinteger value (with a 'u' after the value, as seen in the [influx documentation](https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/#special-characters))
2. You should get a LineFormatError

**Expected behavior**
The message should be parsed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/77795305/113730863-8ad1e780-96f8-11eb-9b30-54c3a96519e5.png)

Regards, 
Martin

**Comment by chinese-soup** [comment]
Hello. 
Is this an InfluxDB 2.0 feature?

I am getting:
```
ERR: {"error":"unable to parse 'User3,meanName=SMOB variableName=\"User3\",avriableId=21i,value=5678u 1': invalid number"}
```

on 
```
┌──[unko@ryzen]─[~/Downloads/influxdb-1.8.4-1/usr/bin]
└──$ ./influxd  version
InfluxDB v1.8.4 (git: 1.8 bc8ec4384eed25436d31045f974bf39f3310fa3c)
```

Thanks.

**Comment by DIZI-BAREILLE** [comment]
Hello,
Sorry for answering so late. Yes it is an Influx2.0 features, thanks for the update ! 
I've seen that the pull request has failed, any idea ?

**Comment by chinese-soup** [comment]
@DIZI-BAREILLE 
Hello. The pull request hasn't failed, the author (@Penlect) just didn't respond yet. 

If you mean the CI, the only thing that failed was the  Windows build which looks to be unrelated to code changes and is some specific Windows CI issue seeing as it fails on some SSL download. 

See here:
https://github.com/Penlect/line-protocol-parser/pull/9/checks?check_run_id=2511944659
https://travis-ci.com/github/Penlect/line-protocol-parser/jobs/503197696#L129

**Comment by DIZI-BAREILLE** [comment]
Ok perfect ! Sorry I misunderstood the message, I'm not really familiar yet with github for now 😅 Thanks again for your help !
